RUN_TYPES = [
    'Maintenance',
    'Transition ',
    'Physics',
    'Deployed Source',
    'External Source',
    'ECA',
    'Diagnostic',
    'Experimental',
    'Supernova',
    'SPARE 1',
    'SPARE 2',
    'TELLIE ',
    'SMELLIE',
    'AMELLIE',
    'PCA',
    'ECA PDST',
    'ECA TSLP',
    'SPARE 3',
    'SPARE 4',
    'SPARE 5',
    'SPARE 6',
    'DCR Activity',
    'Compensation Coils OFF',
    'PMTs OFF',
    'Bubblers ON',
    'Cavity Recirculation ON',
    'SLAssay',
    'Unusual activity',
    'AV Recirculation ON',
    'SPARE 7',
    'SPARE 8',
    'SPARE 9',
]
